-- CreateTable
CREATE TABLE "quarterly_balance_sheet" (
    "symbol" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "quarter" INTEGER NOT NULL,
    "data_type" TEXT NOT NULL,
    "subsidiary_company_id" TEXT NOT NULL DEFAULT '',
    "report_date" DATE NOT NULL,
    "cash_and_equivalents" BIGINT,
    "accounts_receivable" BIGINT,
    "inventory" BIGINT,
    "current_assets" BIGINT,
    "property_plant_equipment" BIGINT,
    "investments_under_equity_method" BIGINT,
    "intangible_assets" BIGINT,
    "non_current_assets" BIGINT,
    "total_assets" BIGINT,
    "short_term_borrowings" BIGINT,
    "accounts_payable" BIGINT,
    "current_liabilities" BIGINT,
    "bonds_payable" BIGINT,
    "long_term_borrowings" BIGINT,
    "non_current_liabilities" BIGINT,
    "total_liabilities" BIGINT,
    "capital_stock" BIGINT,
    "capital_surplus" BIGINT,
    "retained_earnings" BIGINT,
    "other_equity" BIGINT,
    "treasury_stock" BIGINT,
    "equity_attributable_to_parent" BIGINT,
    "non_controlling_interest" BIGINT,
    "total_equity" BIGINT,
    "total_liabilities_and_equity" BIGINT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "quarterly_balance_sheet_pkey" PRIMARY KEY ("symbol","year","quarter","data_type","subsidiary_company_id")
);

