-- AlterTable
ALTER TABLE "quarterly_income_statement" ADD COLUMN     "admin_expenses" BIGINT,
ADD COLUMN     "comprehensive_income_attributable_to_nci" BIGINT,
ADD COLUMN     "comprehensive_income_attributable_to_parent" BIGINT,
ADD COLUMN     "eps_diluted" DECIMAL(10,2),
ADD COLUMN     "finance_costs" BIGINT,
ADD COLUMN     "gross_profit_before_adjustment" BIGINT,
ADD COLUMN     "income_tax_expense" BIGINT,
ADD COLUMN     "interest_income" BIGINT,
ADD COLUMN     "net_income_attributable_to_nci" BIGINT,
ADD COLUMN     "net_income_attributable_to_parent" BIGINT,
ADD COLUMN     "net_income_from_continuing_ops" BIGINT,
ADD COLUMN     "non_operating_income_expenses" BIGINT,
ADD COLUMN     "operating_cost" BIGINT,
ADD COLUMN     "operating_expenses" BIGINT,
ADD COLUMN     "other_comprehensive_income" BIGINT,
ADD COLUMN     "other_income" BIGINT,
ADD COLUMN     "other_non_operating_gains_losses" BIGINT,
ADD COLUMN     "other_operating_gains_losses" BIGINT,
ADD COLUMN     "raw" JSONB,
ADD COLUMN     "rd_expenses" BIGINT,
ADD COLUMN     "selling_expenses" BIGINT,
ADD COLUMN     "share_of_associates_jv_profit" BIGINT,
ADD COLUMN     "total_comprehensive_income" BIGINT;
